import Foundation

extension String {
    var localized: String {
        NSLocalizedString(self, comment: "")
    }
}

enum LocalizationKey {
    static let appTitle = "app.title"
    static let nicknamePlaceholder = "nickname.placeholder"
    static let nicknameContinue = "nickname.continue"
    static let nicknameTaken = "nickname.taken"
    static let nicknameEmpty = "nickname.empty"
    static let nicknameInvalidLength = "nickname.invalid_length"
    static let nicknameInvalidCharacters = "nickname.invalid_characters"
    static let nicknameChecking = "nickname.checking"
    static let nicknameNetworkError = "nickname.network_error"
    static let authModeRegister = "auth.mode.register"
    static let authModeSignIn = "auth.mode.sign_in"
    static let authModeGuest = "auth.mode.guest"
    static let authGuestNicknameLabel = "auth.guest.nickname_label"
    static let authGuestWarning = "auth.guest.warning"
    static let authGuestContinue = "auth.guest.continue"
    static let authGuestCreating = "auth.guest.creating"
    static let authPinPlaceholder = "auth.pin.placeholder"
    static let authConfirmPinPlaceholder = "auth.confirm_pin.placeholder"
    static let authInvalidPin = "auth.invalid_pin"
    static let authPinMismatch = "auth.pin_mismatch"
    static let authInvalidCredentials = "auth.invalid_credentials"
    static let authAccountLocked = "auth.account_locked"
    static let authForgotPin = "auth.forgot_pin"
    static let authCreating = "auth.creating"
    static let authSigningIn = "auth.signing_in"
    static let authSessionExpired = "auth.session_expired"
    static let authServerUpgradeRequired = "auth.server_upgrade_required"
    static let menuStart = "menu.start"
    static let menuLeaderboard = "menu.leaderboard"
    static let menuMyTotal = "menu.my_total"
    static let menuSignOut = "menu.sign_out"
    static let rulesBody = "rules.body"
    static let rulesDontShow = "rules.dont_show"
    static let rulesStart = "rules.start"
    static let resultTitle = "result.title"
    static let resultBack = "result.back"
    static let resultTooShort = "result.too_short"
    static let resultSaving = "result.saving"
    static let resultSaved = "result.saved"
    static let resultSaveFailed = "result.save_failed"
    static let resultRetrySave = "result.retry_save"
    static let leaderboardTitle = "leaderboard.title"
    static let leaderboardModeBestSession = "leaderboard.mode.best_session"
    static let leaderboardModeTotal = "leaderboard.mode.total"
    static let leaderboardEmpty = "leaderboard.empty"
    static let leaderboardOffline = "leaderboard.offline"
    static let leaderboardError = "leaderboard.error"
    static let myTotalTitle = "my_total.title"
    static let myTotalLabel = "my_total.label"
    static let myTotalLoadFailed = "my_total.load_failed"
    static let myTotalSessions = "my_total.sessions"
    static let myTotalNoSessions = "my_total.no_sessions"
    static let commonLoading = "common.loading"
}
